### ISSUE TITLE
Add ability to inject entire secret to environment

### ISSUE THREAD

**Issue by tomjohnburton** [1Password/load-secrets-action#12]
Instead of specifying each secret individually, I would love to be able to just reference the vault and secret, and the action creates all the env vars.

For example:
```
on: push
jobs:
  hello-world:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Load secret
        uses: 1password/load-secrets-action@v1
        with:
          inject_all: true
        env:
          OP_CONNECT_HOST: <Your Connect instance URL>
          OP_CONNECT_TOKEN: ${{ secrets.OP_CONNECT_TOKEN }}
          _: op://app-cicd/hello-world
```

```
$ env
A=123
B=234
C=456
...
```
