### ISSUE TITLE
Unable to fetch secrets

### ISSUE THREAD

**Issue by rockey5520** [1Password/load-secrets-action#24]
Since this morning all my workflow has been failing with the following error, Any support would be super helpful. They were working fine till last week and on a side note, I was able to access secrets via curl to the OP_CONNECT_HOST endpoint

Run 1password/load-secrets-action@v1
/usr/bin/sh -c /home/runner/work/_actions/1password/load-secrets-action/v1/entrypoint.sh
Authenticated with CONNECT 
Archive:  op.zip
 extracting: /usr/local/bin/op.sig   
  inflating: /usr/local/bin/op       
Populating variable: XXX
Error:  2022/12/19 14:11:34 could not read secret op://XXX/XXX/password: could not retrieve vaults: Get "XXX/v1/vaults": unsupported protocol scheme ""
Error: The process '/usr/bin/sh' failed with exit code 1

**Comment by rockey5520** [comment]
I was wondering if anyone could help :)  Here below is the snippet of the action workflow file

all our pipelines stopped working and it would be great to get some hints to solve this issue. Apologies in advance for the rush

```
      - name: Set environment variables
        run: |
          echo "ONE_PASSWORD_GITHUB_ACCESS_TOKEN=${{ env.ENVIRONMENT }}_ONE_PASSWORD_GITHUB_ACCESS_TOKEN" >> $GITHUB_ENV
          echo "OP_CONNECT_HOST=${{ env.ENVIRONMENT }}_OP_CONNECT_HOST" >> $GITHUB_ENV

      - name: Load secret
        id: load_secrets
        uses: 1password/load-secrets-action@v1
        env:
          OP_CONNECT_HOST: 'one-p-LoadB-x-x.x.com'
          OP_CONNECT_TOKEN: ${{ secrets[env.ONE_PASSWORD_GITHUB_ACCESS_TOKEN] }}
          GITHUB_ACTION_USER_ACCESS_KEY: op://Engineering_Staging/GITHUB_ACTION_USER_ACCESS_KEY/password
          GITHUB_ACTION_USER_KEY_ID: op://Engineering_Staging/GITHUB_ACTION_USER_KEY_ID/password
          GITHUB_ACTION_USER_ARN: op://Engineering_Staging/GITHUB_ACTION_USER_ARN/password
          POSTGRES_HOST: op://Engineering_Staging/POSTGRES_HOST/password
          POSTGRES_PORT: op://Engineering_Staging/POSTGRES_PORT/password
          POSTGRES_USER: op://Engineering_Staging/POSTGRES_USER/password
          POSTGRES_DB: op://Engineering_Staging/POSTGRES_DB/password
          POSTGRES_PASSWORD: op://Engineering_Staging/POSTGRES_PASSWORD/password
          S3_BUCKET_STACKS: op://Engineering_Staging/S3_BUCKET_STACKS/password
```
