### ISSUE TITLE
Copy 1Password plain notes file into .env

### ISSUE THREAD

**Issue by whobutsb** [1Password/load-secrets-action#41]
Hello All, 
I'm trying to deploy a Laravel application and have a `.env` saved in to my 1Password vault that I would like to use in my deployment process with github actions.  Currently it looks like so: 

```
      - name: Configure 1Password Connect
        uses: 1password/load-secrets-action/configure@v1
        with:
          # Persist the 1Password Service Account token. This will grant
          # all steps of the job access to the token.
          service-account-token: ${{ secrets.OP_SERVICE_ACCOUNT_TOKEN }}

      # Get ENV content from 1Password
      - name: Load secret
        id: op-load-secret
        uses: 1password/load-secrets-action@v1.2.0
        with:
          export-env: true
        env:
          APP_ENV: "op://MyProject/Staging Environment/notesPlain"

      # Create ENV file
      - name: Copy the secret to .env
        run: 'echo $APP_ENV > .env'
```

When it gets to loading the `.env` file the contents of the file are as so: 
```

**Comment by Rohithgilla12** [comment]
I am currently stuck on this too.
But using this script to unblock, I am not using this action and added a custom script.


```
      - name: Install 1Password Cli
        run: |
          curl https://cache.agilebits.com/dist/1P/op2/pkg/v2.18.0/op_linux_amd64_v2.18.0.zip > op.zip
          unzip op.zip
          sudo mv op /usr/local/bin
          rm op.zip

          op user get --me
        env:
          OP_SERVICE_ACCOUNT_TOKEN: ${{ secrets.OP_SERVICE_ACCOUNT_TOKEN }}

      - name: Get 1Password Secrets
        run: op read op://api/dev/notesPlain > .env
        working-directory: ./api
        env:
          OP_SERVICE_ACCOUNT_TOKEN: ${{ secrets.OP_SERVICE_ACCOUNT_TOKEN }}
```

This works good

**Comment by outragedhuman** [comment]
Same issue here, would be great if there was a way `load-secrets-action` could handle this natively!

**Comment by PauloGoncalvesBH** [comment]
> I am currently stuck on this too. But using this script to unblock, I am not using this action and added a custom script.
> 
> ```
> .........
> ```
> 
> This works good

Another solution using action [1password/install-cli-action](https://github.com/1Password/install-cli-action):

```yaml
  - name: Install 1Password CLI
    uses: 1password/install-cli-action@v1
    with:
      version: 2.18.0

  - name: Get 1Password Secrets
    run: op read op://api/dev/notesPlain > .env
    working-directory: ./api
    env:
      OP_SERVICE_ACCOUNT_TOKEN: ${{ secrets.OP_SERVICE_ACCOUNT_TOKEN }}
```
