### ISSUE TITLE
Add service-account-token to inputs

### ISSUE THREAD

**Issue by yordis** [1Password/load-secrets-action#60]
Ideally use `service-account-token` as part input, so that these type configurations are documented under https://github.com/1Password/load-secrets-action/blob/main/action.yml

```yaml
- name: Load 1Password Secrets
  uses: 1password/load-secrets-action@v1
  with:
    export-env: true
    service-account-token: ${{ secrets.OP_SERVICE_ACCOUNT_TOKEN }} # THIS
  # Instead of the following
  # env:
    # OP_SERVICE_ACCOUNT_TOKEN: ${{ secrets.OP_SERVICE_ACCOUNT_TOKEN }}
```
