### ISSUE TITLE
Node.js 16 deprecation warning when using action

### ISSUE THREAD

**Issue by parente** [1Password/load-secrets-action#61]
GitHub deprecated Node.js v16 use in September 2023. The blog post mentioned in the deprecation warning suggests they'll remove node 16 entirely in Spring 2024.

Using the action like so on 2023-01-22 (when the v1 tag is pointing to v1.3.1):

```
- name: Export 1Password secrets
  uses: 1password/load-secrets-action@v1
  with:
    export-env: true
  env:
    REDACTED: ...
```

results in the following deprecation warning in the GitHub Actions workflow summary:

```
Node.js 16 actions are deprecated. Please update the following actions to use 
Node.js 20: 1password/load-secrets-action@v1. For more information see:
https://github.blog/changelog/2023-09-22-github-actions-transitioning-from-node-16-to-node-20/.
```
