### ISSUE TITLE
Authentication error with environment variables

### ISSUE THREAD

**Issue by tomas-kulhanek** [1Password/load-secrets-action#71]
Whats wrong with this? 
```yaml
      - uses: 1password/load-secrets-action@v2
        with:
          export-env: true
        env:
          OP_SERVICE_ACCOUNT_TOKEN: ${{ secrets.OP_SERVICE_ACCOUNT_TOKEN }}
```

But all actions fall on this message `Authentication error with environment variables: you must set either 1) OP_SERVICE_ACCOUNT_TOKEN, or 2) both OP_CONNECT_HOST and OP_CONNECT_TOKEN.`
