### ISSUE TITLE
Can't load secrets, error message not helpful

### ISSUE THREAD

**Issue by lokeshbhattarai** [1Password/load-secrets-action#74]
With the set up as below I am getting error while loading secret. The error message I get says the token is invalid. However, I'm using a token that has access to the vault I'm using. Is there a way to add/check for debug logs to find out more details? 

```

jobs:
  build-app:
    runs-on: macos-13
    steps:
      - name: Load 1Password secret
        id: onePassword
        uses: 1password/load-secrets-action@v2
        with:
          export-env: true
        env:
          OP_SERVICE_ACCOUNT_TOKEN: ${{ secrets.OP_MOBILE_SERVICE_ACCOUNT }}
          TEST_USER: "op://Test-SDK/TestLogin/username" 
```

This is the error I get

```

Error: could not read secret 'op://Test-SDK/TestLogin/username': error initializing client: Validation: (failed to session.DecodeSACredentials), Server: (failed to DecodeSACredentials), failed to parseToken, format is invalid

```
