### ISSUE TITLE
Cannot get secrets value with `actions/checkout@v4`

### ISSUE THREAD

**Issue by hisamafahri** [1Password/load-secrets-action#96]
After debugging for hours, turns out, if I uses `actions/checkout@v4` the secrets value will be undefined:

- Works
```yml
jobs:
  hello-world:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3 # <========== uses v3

      - name: Load secret
        uses: 1password/load-secrets-action@v2
        with:
          # Export loaded secrets as environment variables
          export-env: true
        env:
          OP_SERVICE_ACCOUNT_TOKEN: ${{ secrets.OP_SERVICE_ACCOUNT_TOKEN }}
          SECRET: op://app-cicd/hello-world/secret

      - name: Print masked secret
        run: 'echo "Secret: $SECRET"'
        # Prints: Secret: ***.                     <========== value returned and masked properly
```

- Doesn't work
```yml
jobs:
  hello-world:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4 # <========== uses v4

      - name: Load secret
        uses: 1password/load-secrets-action@v2
        with:
          # Export loaded secrets as environment variables
          export-env: true
        env:
          OP_SERVICE_ACCOUNT_TOKEN: ${{ secrets.OP_SERVICE_ACCOUNT_TOKEN }}
          SECRET: op://app-cicd/hello-world/secret

      - name: Print masked secret
        run: 'echo "Secret: $SECRET"'
        # Prints: Secret:                             <========== prints nothing
```
---

I have no idea what's happening.
Probably related with https://github.com/1Password/load-secrets-action/issues/92
